<a href="https://colab.research.google.com/github/Dhawaldwivedi/mca-3rd-sem-mmdu-python/blob/main/mca-g1/Numpy_and_Pandas_Basics_mca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# python librares
# numpy - statistical analysis
# pandas - data manipulation
# matplotlib - data visualization
# seaborn - data visualization

Why to use numpy

- faster processing
- less memory consumption
- functionality
- integration with other libraries


In [1]:
#numpy
!pip install numpy

In [2]:
import numpy as np

In [4]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim #for dimension of array

2

In [8]:
arr.shape

(3, 3)

In [9]:
arr.size

9

In [10]:
# zero array

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# ones
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# random function

In [17]:
np.random.random((3,2))*100

array([[99.34351115, 78.19284203],
       [93.22123292, 63.05088651],
       [97.6421639 , 30.28557898]])

In [24]:
np.random.randint(1,6)

2

In [25]:
# arange function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(1,19,4) # stepsize

array([ 1,  5,  9, 13, 17])

In [29]:
np.linspace(1,11,8) # number of elements

array([ 1.        ,  2.42857143,  3.85714286,  5.28571429,  6.71428571,
        8.14285714,  9.57142857, 11.        ])

In [30]:
# flatten
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
p = np.random.random((3,5))
p

array([[0.15466261, 0.47300805, 0.15242295, 0.83659312, 0.73613514],
       [0.33601264, 0.64218892, 0.63427136, 0.48716082, 0.37939618],
       [0.06042662, 0.647695  , 0.45347498, 0.94803111, 0.77575869]])

In [35]:
np.reshape(p,(5,3))

array([[0.15466261, 0.47300805, 0.15242295],
       [0.83659312, 0.73613514, 0.33601264],
       [0.64218892, 0.63427136, 0.48716082],
       [0.37939618, 0.06042662, 0.647695  ],
       [0.45347498, 0.94803111, 0.77575869]])

In [ ]:
p.flatten()

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [38]:
arr-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [40]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [41]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [42]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
int(arr.max())

9

In [44]:
int(arr.min())

1

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
int(arr.sum())

45

In [47]:
arr.max(axis=0) # column wise

array([7, 8, 9])

In [48]:
arr.max(axis=1) # row wise

array([3, 6, 9])

In [49]:
int(arr.trace()) # sum of diagonal elements

15

In [50]:
arr1 =np.array([[2,5,3],
                [4,2,7],
                [3,5,9]])
arr2 =np.array([[1,9,3],
                [2,2,7],
                [7,6,3]])

In [51]:
arr1

array([[2, 5, 3],
       [4, 2, 7],
       [3, 5, 9]])

In [52]:
arr2

array([[1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [53]:
arr3 = arr1+arr2
arr3

array([[ 3, 14,  6],
       [ 6,  4, 14],
       [10, 11, 12]])

In [55]:
# indexing
int(arr3[2,1])

11

In [56]:
arr3

array([[ 3, 14,  6],
       [ 6,  4, 14],
       [10, 11, 12]])

In [57]:
# sorting
np.sort(arr3)

array([[ 3,  6, 14],
       [ 4,  6, 14],
       [10, 11, 12]])

In [59]:
arr4 = np.sort(arr3,axis=1)
arr4

array([[ 3,  6, 14],
       [ 4,  6, 14],
       [10, 11, 12]])

In [60]:
arr5 = np.sort(arr3,axis=0)
arr5

array([[ 3,  4,  6],
       [ 6, 11, 12],
       [10, 14, 14]])

In [61]:
# stack - merges 2 arrays
arr1


array([[2, 5, 3],
       [4, 2, 7],
       [3, 5, 9]])

In [62]:
arr2

array([[1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [63]:
arr3 = np.vstack((arr1,arr2))
arr3

array([[2, 5, 3],
       [4, 2, 7],
       [3, 5, 9],
       [1, 9, 3],
       [2, 2, 7],
       [7, 6, 3]])

In [64]:
arr4 = np.hstack((arr1,arr2))
arr4

array([[2, 5, 3, 1, 9, 3],
       [4, 2, 7, 2, 2, 7],
       [3, 5, 9, 7, 6, 3]])

In [67]:
# split functions
np.hsplit(arr4,3)

[array([[2, 5],
        [4, 2],
        [3, 5]]),
 array([[3, 1],
        [7, 2],
        [9, 7]]),
 array([[9, 3],
        [2, 7],
        [6, 3]])]

In [68]:
np.vsplit(arr3,3)

[array([[2, 5, 3],
        [4, 2, 7]]),
 array([[3, 5, 9],
        [1, 9, 3]]),
 array([[2, 2, 7],
        [7, 6, 3]])]

Normalization using Numpy

In [ ]:
# 12 , 22, 35, 56, 78, 89
#   6 , 5, 4, 3, 2, 1

In [69]:
import numpy as np
data = np.array([1,2,39,400,5])

In [70]:
min_val = np.min(data)
max_val = np.max(data)
print(min_val)
print(max_val)

1
400


In [71]:
normalized_arr = (data-min_val)/(max_val-min_val)
normalized_arr

array([0.        , 0.00250627, 0.0952381 , 1.        , 0.01002506])

Explore About Z-Score Normalization

In [72]:
data

array([  1,   2,  39, 400,   5])

In [73]:
mean_val = np.mean(data)
std_val = np.std(data)

In [74]:
normalize_val= (data-mean_val)/std_val

In [75]:
normalize_val

array([-0.56687821, -0.56046556, -0.32319753,  1.99176893, -0.54122762])

# Pandas

In [76]:
# importing
import pandas as pd

In [77]:
data = [1,2,3,4]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [78]:
type(s)

pandas.core.series.Series

In [79]:
# create a series through dictionary
dct = {'a':1,'b':2,'c':3}
series_dct = pd.Series(dct)
series_dct

a    1
b    2
c    3
dtype: int64

In [80]:
data = [1,2,3]
Index = ['a','b','c']
series = pd.Series(data,Index)
series

a    1
b    2
c    3
dtype: int64

In [81]:
# dataframe
# creating a dataframe from a dictionary of list
data = {'Name':['Krish','John','Jack'],
        'Age':[23,34,43],
        'City':['Noida','New York','Florida']
        }
df= pd.DataFrame(data)
df

Name  Age      City
0  Krish   23     Noida
1   John   34  New York
2   Jack   43   Florida

In [82]:
df['City']

0       Noida
1    New York
2     Florida
Name: City, dtype: object

In [85]:
# loc - label based
print(df.loc[2,'Age'])

43


In [86]:
#iloc - integer based
df.iloc[2,1]

np.int64(43)

In [87]:
# adding a column
df['salary']= [1000,2000,3000]

In [88]:
df

Name  Age      City  salary
0  Krish   23     Noida    1000
1   John   34  New York    2000
2   Jack   43   Florida    3000

In [89]:
df.drop('salary', axis=1, inplace=True)
df

Name  Age      City
0  Krish   23     Noida
1   John   34  New York
2   Jack   43   Florida

In [90]:
## Add age to the column
df['Age']=df['Age']+1
df

Name  Age      City
0  Krish   24     Noida
1   John   35  New York
2   Jack   44   Florida

In [91]:
# load the sales data
df = pd.read_csv('/content/sales_data (1).csv')

In [92]:
df.head()

Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  
0           2      999.99        1999.98  North America    Credit Card  
1           1      499.99         499.99         Europe         PayPal  
2           3       69.99         209.97           Asia     Debit Card  
3           4       15.99          63.96  North America    Credit Card  
4           1       89.99          89.99         Europe         PayPal

In [93]:
# checking info shape and describe
df.shape

(240, 9)

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Transaction ID    240 non-null    int64  
 1   Date              240 non-null    object 
 2   Product Category  240 non-null    object 
 3   Product Name      240 non-null    object 
 4   Units Sold        240 non-null    int64  
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object 
 8   Payment Method    240 non-null    object 
dtypes: float64(2), int64(2), object(5)
memory usage: 17.0+ KB


In [95]:
df.describe()

Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [97]:
# checking for null values
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [98]:
df.head()

Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  
0           2      999.99        1999.98  North America    Credit Card  
1           1      499.99         499.99         Europe         PayPal  
2           3       69.99         209.97           Asia     Debit Card  
3           4       15.99          63.96  North America    Credit Card  
4           1       89.99          89.99         Europe         PayPal

In [102]:
# Filter data based on conditions
df[df['Region']=='Europe']

Transaction ID        Date Product Category  \
1             10002  2024-01-02  Home Appliances   
4             10005  2024-01-05  Beauty Products   
7             10008  2024-01-08  Home Appliances   
10            10011  2024-01-11  Beauty Products   
13            10014  2024-01-14  Home Appliances   
..              ...         ...              ...   
226           10227  2024-08-14  Beauty Products   
229           10230  2024-08-17  Home Appliances   
232           10233  2024-08-20  Beauty Products   
235           10236  2024-08-23  Home Appliances   
238           10239  2024-08-26  Beauty Products   

                                        Product Name  Units Sold  Unit Price  \
1                                   Dyson V11 Vacuum           1      499.99   
4                            Neutrogena Skincare Set           1       89.99   
7                               Blueair Classic 480i           2      599.99   
10                              Chanel No. 5 Perfume           1      129.99   
13                       Keurig K-Elite Coffee Maker           1      189.99   
..                                               ...         ...         ...   
226         The Ordinary Caffeine Solution 5% + EGCG           1        6.70   
229                             Anova Precision Oven           1      599.00   
232                        Fresh Sugar Lip Treatment           1       24.00   
235  Nespresso Vertuo Next Coffee and Espresso Maker           1      159.99   
238             Sunday Riley Luna Sleeping Night Oil           1       55.00   

     Total Revenue  Region Payment Method  
1           499.99  Europe         PayPal  
4            89.99  Europe         PayPal  
7          1199.98  Europe         PayPal  
10          129.99  Europe         PayPal  
13          189.99  Europe         PayPal  
..             ...     ...            ...  
226           6.70  Europe         PayPal  
229         599.00  Europe         PayPal  
232          24.00  Europe         PayPal  
235         159.99  Europe         PayPal  
238          55.00  Europe         PayPal  

[80 rows x 9 columns]

In [103]:
# Sort by column
df.sort_values(by='Total Revenue', ascending=False)

Transaction ID        Date Product Category  \
102           10103  2024-04-12      Electronics   
85            10086  2024-03-26  Home Appliances   
6             10007  2024-01-07      Electronics   
216           10217  2024-08-04      Electronics   
0             10001  2024-01-01      Electronics   
..              ...         ...              ...   
166           10167  2024-06-15  Beauty Products   
112           10113  2024-04-22  Beauty Products   
136           10137  2024-05-16  Beauty Products   
226           10227  2024-08-14  Beauty Products   
106           10107  2024-04-16  Beauty Products   

                                    Product Name  Units Sold  Unit Price  \
102                          Canon EOS R5 Camera           1     3899.99   
85                                    LG OLED TV           2     1299.99   
6                            MacBook Pro 16-inch           1     2499.99   
216                    Apple MacBook Pro 16-inch           1     2399.00   
0                                  iPhone 14 Pro           2      999.99   
..                                           ...         ...         ...   
166             Neutrogena Hydro Boost Water Gel           1       16.99   
112  Biore UV Aqua Rich Watery Essence Sunscreen           1       15.00   
136           The Ordinary Hyaluronic Acid Serum           1        6.80   
226     The Ordinary Caffeine Solution 5% + EGCG           1        6.70   
106               The Ordinary Niacinamide Serum           1        6.50   

     Total Revenue         Region Payment Method  
102        3899.99  North America    Credit Card  
85         2599.98         Europe         PayPal  
6          2499.99  North America    Credit Card  
216        2399.00  North America    Credit Card  
0          1999.98  North America    Credit Card  
..             ...            ...            ...  
166          16.99         Europe         PayPal  
112          15.00         Europe         PayPal  
136           6.80         Europe         PayPal  
226           6.70         Europe         PayPal  
106           6.50         Europe         PayPal  

[240 rows x 9 columns]

In [104]:
# calculate the total revenue region vise
df.groupby('Region')['Total Revenue'].sum()

Region
Asia             22455.45
Europe           21268.06
North America    36844.34
Name: Total Revenue, dtype: float64

In [ ]:
# display only product name and total revenue where unit sold is less than 5

In [ ]:
# find top 3 products with highest total revenue